/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppCollectionsRouteImport } from './routes/_app/collections'
import { Route as AppEntitiesRouteImport } from './routes/_app/entities'
import { Route as AppSavedSearchesRouteImport } from './routes/_app/saved-searches'
import { Route as AppSearchesRouteImport } from './routes/_app/searches'
import { Route as ApiAgentRunRouteImport } from './routes/api/agent-run'
import { Route as ApiColumnsRouteImport } from './routes/api/columns'
import { Route as ApiEntitiesRouteImport } from './routes/api/entities'
import { Route as ApiEntitiesExportRouteImport } from './routes/api/entities-export'
import { Route as ApiRecentSearchesRouteImport } from './routes/api/recent-searches'
import { Route as ApiSavedSearchesRouteImport } from './routes/api/saved-searches'
import { Route as ApiSearchRouteImport } from './routes/api/search'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCollectionsRoute = AppCollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => AppRoute,
} as any)
const AppEntitiesRoute = AppEntitiesRouteImport.update({
  id: '/entities',
  path: '/entities',
  getParentRoute: () => AppRoute,
} as any)
const AppSavedSearchesRoute = AppSavedSearchesRouteImport.update({
  id: '/saved-searches',
  path: '/saved-searches',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchesRoute = AppSearchesRouteImport.update({
  id: '/searches',
  path: '/searches',
  getParentRoute: () => AppRoute,
} as any)
const ApiAgentRunRoute = ApiAgentRunRouteImport.update({
  id: '/api/agent-run',
  path: '/api/agent-run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiColumnsRoute = ApiColumnsRouteImport.update({
  id: '/api/columns',
  path: '/api/columns',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEntitiesRoute = ApiEntitiesRouteImport.update({
  id: '/api/entities',
  path: '/api/entities',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEntitiesExportRoute = ApiEntitiesExportRouteImport.update({
  id: '/api/entities-export',
  path: '/api/entities-export',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRecentSearchesRoute = ApiRecentSearchesRouteImport.update({
  id: '/api/recent-searches',
  path: '/api/recent-searches',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSavedSearchesRoute = ApiSavedSearchesRouteImport.update({
  id: '/api/saved-searches',
  path: '/api/saved-searches',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/collections': typeof AppCollectionsRoute
  '/entities': typeof AppEntitiesRoute
  '/saved-searches': typeof AppSavedSearchesRoute
  '/searches': typeof AppSearchesRoute
  '/api/agent-run': typeof ApiAgentRunRoute
  '/api/columns': typeof ApiColumnsRoute
  '/api/entities': typeof ApiEntitiesRoute
  '/api/entities-export': typeof ApiEntitiesExportRoute
  '/api/recent-searches': typeof ApiRecentSearchesRoute
  '/api/saved-searches': typeof ApiSavedSearchesRoute
  '/api/search': typeof ApiSearchRoute
}
export interface FileRoutesByTo {
  '/collections': typeof AppCollectionsRoute
  '/entities': typeof AppEntitiesRoute
  '/saved-searches': typeof AppSavedSearchesRoute
  '/searches': typeof AppSearchesRoute
  '/api/agent-run': typeof ApiAgentRunRoute
  '/api/columns': typeof ApiColumnsRoute
  '/api/entities': typeof ApiEntitiesRoute
  '/api/entities-export': typeof ApiEntitiesExportRoute
  '/api/recent-searches': typeof ApiRecentSearchesRoute
  '/api/saved-searches': typeof ApiSavedSearchesRoute
  '/api/search': typeof ApiSearchRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/collections': typeof AppCollectionsRoute
  '/_app/entities': typeof AppEntitiesRoute
  '/_app/saved-searches': typeof AppSavedSearchesRoute
  '/_app/searches': typeof AppSearchesRoute
  '/api/agent-run': typeof ApiAgentRunRoute
  '/api/columns': typeof ApiColumnsRoute
  '/api/entities': typeof ApiEntitiesRoute
  '/api/entities-export': typeof ApiEntitiesExportRoute
  '/api/recent-searches': typeof ApiRecentSearchesRoute
  '/api/saved-searches': typeof ApiSavedSearchesRoute
  '/api/search': typeof ApiSearchRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/collections'
    | '/entities'
    | '/saved-searches'
    | '/searches'
    | '/api/agent-run'
    | '/api/columns'
    | '/api/entities'
    | '/api/entities-export'
    | '/api/recent-searches'
    | '/api/saved-searches'
    | '/api/search'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/collections'
    | '/entities'
    | '/saved-searches'
    | '/searches'
    | '/api/agent-run'
    | '/api/columns'
    | '/api/entities'
    | '/api/entities-export'
    | '/api/recent-searches'
    | '/api/saved-searches'
    | '/api/search'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/_app/collections'
    | '/_app/entities'
    | '/_app/saved-searches'
    | '/_app/searches'
    | '/api/agent-run'
    | '/api/columns'
    | '/api/entities'
    | '/api/entities-export'
    | '/api/recent-searches'
    | '/api/saved-searches'
    | '/api/search'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ApiAgentRunRoute: typeof ApiAgentRunRoute
  ApiColumnsRoute: typeof ApiColumnsRoute
  ApiEntitiesRoute: typeof ApiEntitiesRoute
  ApiEntitiesExportRoute: typeof ApiEntitiesExportRoute
  ApiRecentSearchesRoute: typeof ApiRecentSearchesRoute
  ApiSavedSearchesRoute: typeof ApiSavedSearchesRoute
  ApiSearchRoute: typeof ApiSearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/collections': {
      id: '/_app/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof AppCollectionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/entities': {
      id: '/_app/entities'
      path: '/entities'
      fullPath: '/entities'
      preLoaderRoute: typeof AppEntitiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/saved-searches': {
      id: '/_app/saved-searches'
      path: '/saved-searches'
      fullPath: '/saved-searches'
      preLoaderRoute: typeof AppSavedSearchesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/searches': {
      id: '/_app/searches'
      path: '/searches'
      fullPath: '/searches'
      preLoaderRoute: typeof AppSearchesRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/agent-run': {
      id: '/api/agent-run'
      path: '/api/agent-run'
      fullPath: '/api/agent-run'
      preLoaderRoute: typeof ApiAgentRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/columns': {
      id: '/api/columns'
      path: '/api/columns'
      fullPath: '/api/columns'
      preLoaderRoute: typeof ApiColumnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/entities': {
      id: '/api/entities'
      path: '/api/entities'
      fullPath: '/api/entities'
      preLoaderRoute: typeof ApiEntitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/entities-export': {
      id: '/api/entities-export'
      path: '/api/entities-export'
      fullPath: '/api/entities-export'
      preLoaderRoute: typeof ApiEntitiesExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/recent-searches': {
      id: '/api/recent-searches'
      path: '/api/recent-searches'
      fullPath: '/api/recent-searches'
      preLoaderRoute: typeof ApiRecentSearchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/saved-searches': {
      id: '/api/saved-searches'
      path: '/api/saved-searches'
      fullPath: '/api/saved-searches'
      preLoaderRoute: typeof ApiSavedSearchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppCollectionsRoute: typeof AppCollectionsRoute
  AppEntitiesRoute: typeof AppEntitiesRoute
  AppSavedSearchesRoute: typeof AppSavedSearchesRoute
  AppSearchesRoute: typeof AppSearchesRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCollectionsRoute: AppCollectionsRoute,
  AppEntitiesRoute: AppEntitiesRoute,
  AppSavedSearchesRoute: AppSavedSearchesRoute,
  AppSearchesRoute: AppSearchesRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ApiAgentRunRoute: ApiAgentRunRoute,
  ApiColumnsRoute: ApiColumnsRoute,
  ApiEntitiesRoute: ApiEntitiesRoute,
  ApiEntitiesExportRoute: ApiEntitiesExportRoute,
  ApiRecentSearchesRoute: ApiRecentSearchesRoute,
  ApiSavedSearchesRoute: ApiSavedSearchesRoute,
  ApiSearchRoute: ApiSearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
