/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as EntitiesRouteImport } from './routes/entities'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as SavedSearchesRouteImport } from './routes/saved-searches'
import { Route as SearchesRouteImport } from './routes/searches'
import { Route as SettingsRouteImport } from './routes/settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const EntitiesRoute = EntitiesRouteImport.update({
  id: '/entities',
  path: '/entities',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedSearchesRoute = SavedSearchesRouteImport.update({
  id: '/saved-searches',
  path: '/saved-searches',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchesRoute = SearchesRouteImport.update({
  id: '/searches',
  path: '/searches',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collections': typeof CollectionsRoute
  '/entities': typeof EntitiesRoute
  '/history': typeof HistoryRoute
  '/saved-searches': typeof SavedSearchesRoute
  '/searches': typeof SearchesRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collections': typeof CollectionsRoute
  '/entities': typeof EntitiesRoute
  '/history': typeof HistoryRoute
  '/saved-searches': typeof SavedSearchesRoute
  '/searches': typeof SearchesRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/collections': typeof CollectionsRoute
  '/entities': typeof EntitiesRoute
  '/history': typeof HistoryRoute
  '/saved-searches': typeof SavedSearchesRoute
  '/searches': typeof SearchesRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/collections'
    | '/entities'
    | '/history'
    | '/saved-searches'
    | '/searches'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/collections'
    | '/entities'
    | '/history'
    | '/saved-searches'
    | '/searches'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/collections'
    | '/entities'
    | '/history'
    | '/saved-searches'
    | '/searches'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollectionsRoute: typeof CollectionsRoute
  EntitiesRoute: typeof EntitiesRoute
  HistoryRoute: typeof HistoryRoute
  SavedSearchesRoute: typeof SavedSearchesRoute
  SearchesRoute: typeof SearchesRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities': {
      id: '/entities'
      path: '/entities'
      fullPath: '/entities'
      preLoaderRoute: typeof EntitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved-searches': {
      id: '/saved-searches'
      path: '/saved-searches'
      fullPath: '/saved-searches'
      preLoaderRoute: typeof SavedSearchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/searches': {
      id: '/searches'
      path: '/searches'
      fullPath: '/searches'
      preLoaderRoute: typeof SearchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollectionsRoute: CollectionsRoute,
  EntitiesRoute: EntitiesRoute,
  HistoryRoute: HistoryRoute,
  SavedSearchesRoute: SavedSearchesRoute,
  SearchesRoute: SearchesRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
